/**
 * Seed 30 more toy reviews to Sanity CMS (bringing total to 50).
 * Run with: SANITY_API_TOKEN="..." node scripts/seed-30-more.mjs
 */

import { createClient } from '@sanity/client';

const client = createClient({
  projectId: 'ofvgjgsi',
  dataset: 'production',
  apiVersion: '2024-01-01',
  useCdn: false,
  token: process.env.SANITY_API_TOKEN,
});

function computeSafetyScore(ms, cr, rh, cp) {
  return Math.round(ms * 0.30 + cr * 0.30 + rh * 0.20 + cp * 0.20);
}

function computeDevelopmentScore(motor, cognitive, sensory) {
  return Math.round(motor * 0.40 + cognitive * 0.35 + sensory * 0.25);
}

const reviews = [
  {
    _id: 'review-lego-duplo-brick-box',
    _type: 'toyReview',
    productName: 'LEGO DUPLO Classic Brick Box',
    brand: 'LEGO DUPLO',
    slug: { _type: 'slug', current: 'lego-duplo-classic-brick-box' },
    ageRange: { minMonths: 18, maxMonths: 60 },
    category: { _type: 'reference', _ref: 'cat-building' },
    materialSafety: 92, chokingRisk: 94, recallHistory: 90, certificationPresence: 96,
    motorSkills: 88, cognitiveSkills: 85, sensoryEngagement: 72,
    materials: ['ABS plastic', 'BPA-free', 'phthalate-free'],
    chokingHazardAssessment: 'All DUPLO bricks are 8x larger than standard LEGO. No choking hazard for 18m+. Designed specifically for toddler hands.',
    certifications: ['ASTM F963', 'EN-71', 'CPSIA', 'ISO 8124'],
    pros: ['Large bricks safe for toddlers', 'Endless building combinations', 'Compatible with all DUPLO sets', 'Durable ABS plastic'],
    cons: ['Expensive per brick', 'Storage container not very sturdy', 'Limited special pieces in basic set'],
    alternativeId: 'review-magna-tiles-100',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B00NHQF6MG', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-magna-tiles-100',
    _type: 'toyReview',
    productName: 'Magna-Tiles Clear Colors 100 Piece Set',
    brand: 'Magna-Tiles',
    slug: { _type: 'slug', current: 'magna-tiles-clear-colors-100pc' },
    ageRange: { minMonths: 36, maxMonths: 96 },
    category: { _type: 'reference', _ref: 'cat-building' },
    materialSafety: 90, chokingRisk: 86, recallHistory: 92, certificationPresence: 94,
    motorSkills: 90, cognitiveSkills: 92, sensoryEngagement: 78,
    materials: ['ABS plastic', 'sealed magnets', 'BPA-free'],
    chokingHazardAssessment: 'Magnets are fully sealed inside plastic tiles. Tiles are 3+ inches. No small parts. Ages 3+ recommended.',
    certifications: ['ASTM F963', 'CPSIA', 'CE mark'],
    pros: ['Open-ended STEM play', 'Teaches geometry concepts', 'Beautiful translucent colors', 'Extremely durable construction'],
    cons: ['Premium price point', 'Magnets can weaken over years', 'Smaller tiles in set not for under 3'],
    alternativeId: 'review-lego-duplo-brick-box',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B000CBSNRY', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-tegu-14-piece',
    _type: 'toyReview',
    productName: 'Tegu 14-Piece Magnetic Wooden Blocks',
    brand: 'Tegu',
    slug: { _type: 'slug', current: 'tegu-14-piece-magnetic-blocks' },
    ageRange: { minMonths: 12, maxMonths: 72 },
    category: { _type: 'reference', _ref: 'cat-building' },
    materialSafety: 96, chokingRisk: 88, recallHistory: 98, certificationPresence: 94,
    motorSkills: 86, cognitiveSkills: 84, sensoryEngagement: 76,
    materials: ['Honduran hardwood', 'water-based lacquer', 'sealed internal magnets'],
    chokingHazardAssessment: 'All blocks exceed 1.75 inches. Magnets permanently sealed inside wood. No coatings that peel. Safe for 12m+.',
    certifications: ['ASTM F963', 'CPSIA', 'EN-71', 'FSC-certified wood'],
    pros: ['Beautiful natural wood aesthetic', 'Internal magnets add building fun', 'Sustainably sourced hardwood', 'Safe from 1 year'],
    cons: ['Expensive for 14 pieces', 'Limited shapes in starter set', 'Heavy for young toddlers'],
    alternativeId: 'review-grimms-rainbow',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B007PRNBUY', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-plantoys-stacking-ring',
    _type: 'toyReview',
    productName: 'PlanToys Stacking Ring',
    brand: 'PlanToys',
    slug: { _type: 'slug', current: 'plantoys-stacking-ring' },
    ageRange: { minMonths: 12, maxMonths: 36 },
    category: { _type: 'reference', _ref: 'cat-educational' },
    materialSafety: 96, chokingRisk: 90, recallHistory: 98, certificationPresence: 94,
    motorSkills: 82, cognitiveSkills: 78, sensoryEngagement: 70,
    materials: ['PlanWood (recycled rubberwood)', 'organic pigments', 'E-zero formaldehyde-free glue'],
    chokingHazardAssessment: 'All rings are 2.5+ inches diameter. Pole has rounded top. No detachable small parts. Safe for 12m+.',
    certifications: ['ASTM F963', 'EN-71', 'ISO 8124'],
    pros: ['Eco-friendly PlanWood material', 'Teaches size sequencing', 'Beautiful muted colors', 'Durable construction'],
    cons: ['Limited to stacking play', 'Muted colors less stimulating for some babies', 'Expensive for simple toy'],
    alternativeId: 'review-hape-shape-sorter-xylophone',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B001XDZUUW', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-leapfrog-learning-friends',
    _type: 'toyReview',
    productName: 'LeapFrog Learning Friends 100 Words Book',
    brand: 'LeapFrog',
    slug: { _type: 'slug', current: 'leapfrog-learning-friends-book' },
    ageRange: { minMonths: 18, maxMonths: 48 },
    category: { _type: 'reference', _ref: 'cat-educational' },
    materialSafety: 86, chokingRisk: 88, recallHistory: 90, certificationPresence: 88,
    motorSkills: 72, cognitiveSkills: 92, sensoryEngagement: 80,
    materials: ['BPA-free plastic', 'electronic components', 'cardboard pages'],
    chokingHazardAssessment: 'All buttons are flush-mounted. Pages are thick and sturdy. Battery compartment is screw-secured. Safe for 18m+.',
    certifications: ['ASTM F963', 'CPSIA', 'FCC compliant'],
    pros: ['Bilingual English/Spanish', 'Touch-activated words build vocabulary', 'Categories teach organization', 'Fun sound effects'],
    cons: ['Battery dependent', 'Repetitive sounds can annoy parents', 'Electronic components limit lifespan'],
    alternativeId: 'review-vtech-sit-to-stand',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B00CQHZU4G', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-baby-einstein-tunes',
    _type: 'toyReview',
    productName: 'Baby Einstein Take Along Tunes Musical Toy',
    brand: 'Baby Einstein',
    slug: { _type: 'slug', current: 'baby-einstein-take-along-tunes' },
    ageRange: { minMonths: 3, maxMonths: 24 },
    category: { _type: 'reference', _ref: 'cat-sensory' },
    materialSafety: 86, chokingRisk: 90, recallHistory: 84, certificationPresence: 86,
    motorSkills: 70, cognitiveSkills: 72, sensoryEngagement: 90,
    materials: ['BPA-free plastic', 'electronic speaker', 'rubber grip'],
    chokingHazardAssessment: 'Caterpillar handle is large and round. Volume control is flush. Battery compartment screw-secured. Safe for 3m+.',
    certifications: ['ASTM F963', 'CPSIA', 'FCC compliant'],
    pros: ['Classical melodies introduce music', 'Easy grip handle', 'Volume control for parents', 'Colorful light-up star'],
    cons: ['Limited 7 melodies', 'Battery life is short', 'Plastic feels cheap'],
    alternativeId: 'review-vtech-kidibeats',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B000YDDF6O', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-sophie-la-girafe',
    _type: 'toyReview',
    productName: 'Sophie la Girafe Teether',
    brand: 'Sophie la Girafe',
    slug: { _type: 'slug', current: 'sophie-la-girafe-teether' },
    ageRange: { minMonths: 0, maxMonths: 18 },
    category: { _type: 'reference', _ref: 'cat-sensory' },
    materialSafety: 92, chokingRisk: 88, recallHistory: 86, certificationPresence: 92,
    motorSkills: 72, cognitiveSkills: 60, sensoryEngagement: 94,
    materials: ['100% natural rubber', 'food-grade paint'],
    chokingHazardAssessment: 'One-piece rubber construction. Legs and head are too large to fit in mouth fully. Squeaker is sealed. Safe from birth.',
    certifications: ['CE mark', 'EN-71', 'FDA food-grade'],
    pros: ['100% natural rubber', 'Stimulates all 5 senses', 'Easy to grip legs and neck', 'Iconic trusted design since 1961'],
    cons: ['Expensive for a teether', 'Can develop mold if water enters squeaker hole', 'Strong rubber smell initially'],
    alternativeId: 'review-nuby-teething-keys',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B000IDSLOG', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-lamaze-freddie',
    _type: 'toyReview',
    productName: 'Lamaze Freddie the Firefly Clip-On Toy',
    brand: 'Lamaze',
    slug: { _type: 'slug', current: 'lamaze-freddie-the-firefly' },
    ageRange: { minMonths: 0, maxMonths: 24 },
    category: { _type: 'reference', _ref: 'cat-sensory' },
    materialSafety: 88, chokingRisk: 86, recallHistory: 90, certificationPresence: 86,
    motorSkills: 78, cognitiveSkills: 70, sensoryEngagement: 92,
    materials: ['polyester fabric', 'BPA-free plastic rings', 'crinkle material'],
    chokingHazardAssessment: 'Clip-on is adult-strength only. All fabric parts are sewn securely. Teether ring is oversized. Safe from birth.',
    certifications: ['ASTM F963', 'CPSIA', 'CE mark'],
    pros: ['Multiple textures and sounds', 'Clip attaches to stroller or car seat', 'High contrast colors for newborns', 'Machine washable'],
    cons: ['Clip can be hard to open one-handed', 'Crinkle sound diminishes with washing', 'Fabric absorbs drool quickly'],
    alternativeId: 'review-skip-hop-bandana-buddies',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B004LRJAHI', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-nuby-teething-keys',
    _type: 'toyReview',
    productName: 'Nuby IcyBite Teething Keys',
    brand: 'Nuby',
    slug: { _type: 'slug', current: 'nuby-icybite-teething-keys' },
    ageRange: { minMonths: 3, maxMonths: 18 },
    category: { _type: 'reference', _ref: 'cat-sensory' },
    materialSafety: 86, chokingRisk: 90, recallHistory: 88, certificationPresence: 84,
    motorSkills: 68, cognitiveSkills: 58, sensoryEngagement: 88,
    materials: ['BPA-free plastic', 'purICE gel', 'food-grade materials'],
    chokingHazardAssessment: 'Keys are large and connected to ring. Ring handle is too large to swallow. Gel is sealed and non-toxic. Safe for 3m+.',
    certifications: ['ASTM F963', 'CPSIA', 'BPA-free certified'],
    pros: ['Cooling gel soothes teething pain', 'Multiple textures for gum massage', 'Very affordable', 'Easy to grip ring handle'],
    cons: ['Must refrigerate for cooling effect', 'Gel can become warm quickly', 'Limited play value beyond teething'],
    alternativeId: 'review-sophie-la-girafe',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B003N9M6YI', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-play-doh-starter',
    _type: 'toyReview',
    productName: 'Play-Doh Starter Set',
    brand: 'Play-Doh',
    slug: { _type: 'slug', current: 'play-doh-starter-set' },
    ageRange: { minMonths: 24, maxMonths: 72 },
    category: { _type: 'reference', _ref: 'cat-educational' },
    materialSafety: 82, chokingRisk: 78, recallHistory: 88, certificationPresence: 86,
    motorSkills: 90, cognitiveSkills: 85, sensoryEngagement: 88,
    materials: ['wheat flour', 'water', 'salt', 'food-grade colorants'],
    chokingHazardAssessment: 'Compound is non-toxic but not edible. Tools are large and rounded. Contains wheat (allergen). Ages 2+ only.',
    certifications: ['ASTM D-4236', 'AP certified non-toxic', 'CPSIA'],
    pros: ['Unlimited creative possibilities', 'Strengthens hand muscles', 'Non-toxic formula', 'Extremely affordable'],
    cons: ['Contains wheat (allergen concern)', 'Dries out if not sealed', 'Can stain fabric and carpet'],
    alternativeId: 'review-crayola-finger-paints',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B09BW7LGMG', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-edushape-sensory-balls',
    _type: 'toyReview',
    productName: 'Edushape Sensory Ball Mega Pack',
    brand: 'Edushape',
    slug: { _type: 'slug', current: 'edushape-sensory-ball-set' },
    ageRange: { minMonths: 6, maxMonths: 36 },
    category: { _type: 'reference', _ref: 'cat-sensory' },
    materialSafety: 88, chokingRisk: 92, recallHistory: 90, certificationPresence: 86,
    motorSkills: 76, cognitiveSkills: 65, sensoryEngagement: 94,
    materials: ['BPA-free PVC', 'phthalate-free', 'latex-free'],
    chokingHazardAssessment: 'All balls are 4+ inches diameter. Soft and squeezable. No small parts. One-piece construction. Safe for 6m+.',
    certifications: ['ASTM F963', 'CPSIA', 'EN-71'],
    pros: ['Unique nubby textures stimulate touch', 'Large easy-to-grab size', 'Bright translucent colors', 'Multiple textures in set'],
    cons: ['Can deflate if punctured', 'Rubber smell when new', 'Texture attracts dirt and hair'],
    alternativeId: 'review-infantino-textured-balls',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B000LRUOSG', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-kiwico-panda-crate',
    _type: 'toyReview',
    productName: 'KiwiCo Panda Crate (0-24 months)',
    brand: 'KiwiCo',
    slug: { _type: 'slug', current: 'kiwico-panda-crate' },
    ageRange: { minMonths: 0, maxMonths: 24 },
    category: { _type: 'reference', _ref: 'cat-educational' },
    materialSafety: 90, chokingRisk: 88, recallHistory: 96, certificationPresence: 90,
    motorSkills: 86, cognitiveSkills: 88, sensoryEngagement: 82,
    materials: ['wood', 'organic cotton', 'food-grade silicone', 'recycled cardboard'],
    chokingHazardAssessment: 'Age-appropriate items in each box. Tested to CPSIA standards. Detailed parent guide included. Items vary by age stage.',
    certifications: ['ASTM F963', 'CPSIA', 'CPSC compliant'],
    pros: ['Expert-designed developmental activities', 'New items each month', 'Detailed play guides included', 'High-quality materials'],
    cons: ['Subscription model ($36+/month)', 'Cannot choose specific items', 'Some items have short useful window'],
    alternativeId: 'review-lovevery-play-kit',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B0BXMWJGBY', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-lego-duplo-number-train',
    _type: 'toyReview',
    productName: 'LEGO DUPLO Number Train - Learn to Count',
    brand: 'LEGO DUPLO',
    slug: { _type: 'slug', current: 'lego-duplo-number-train' },
    ageRange: { minMonths: 18, maxMonths: 60 },
    category: { _type: 'reference', _ref: 'cat-educational' },
    materialSafety: 92, chokingRisk: 92, recallHistory: 92, certificationPresence: 96,
    motorSkills: 84, cognitiveSkills: 90, sensoryEngagement: 74,
    materials: ['ABS plastic', 'BPA-free', 'phthalate-free'],
    chokingHazardAssessment: 'DUPLO scale bricks. Number bricks are 2x2 DUPLO size. Minifigures are large. All parts safe for 18m+.',
    certifications: ['ASTM F963', 'EN-71', 'CPSIA', 'ISO 8124'],
    pros: ['Teaches numbers 0-9', 'Rolling wheels add motion play', 'Compatible with DUPLO system', 'Includes character figures'],
    cons: ['Limited brick count (23 pieces)', 'Number bricks can be confusing upside down', 'Small set for the price'],
    alternativeId: 'review-lego-duplo-brick-box',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B08G4GPS5Q', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-magna-tiles-stardust',
    _type: 'toyReview',
    productName: 'Magna-Tiles Stardust 15-Piece Set',
    brand: 'Magna-Tiles',
    slug: { _type: 'slug', current: 'magna-tiles-stardust-15pc' },
    ageRange: { minMonths: 36, maxMonths: 96 },
    category: { _type: 'reference', _ref: 'cat-building' },
    materialSafety: 90, chokingRisk: 86, recallHistory: 92, certificationPresence: 94,
    motorSkills: 86, cognitiveSkills: 88, sensoryEngagement: 82,
    materials: ['ABS plastic', 'sealed magnets', 'glitter encapsulation', 'BPA-free'],
    chokingHazardAssessment: 'Same safety as original Magna-Tiles. Glitter is sealed inside tiles. Magnets fully enclosed. Ages 3+.',
    certifications: ['ASTM F963', 'CPSIA', 'CE mark'],
    pros: ['Gorgeous glitter and mirror tiles', 'Compatible with all Magna-Tiles', 'Spark imaginative building', 'Sealed glitter is safe'],
    cons: ['Only 15 pieces for high price', 'Glitter tiles can be harder to see through', 'Small set needs supplementing'],
    alternativeId: 'review-magna-tiles-100',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B09DP6ND45', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-tegu-sunset-24',
    _type: 'toyReview',
    productName: 'Tegu Sunset 24-Piece Magnetic Block Set',
    brand: 'Tegu',
    slug: { _type: 'slug', current: 'tegu-sunset-24-piece' },
    ageRange: { minMonths: 12, maxMonths: 96 },
    category: { _type: 'reference', _ref: 'cat-building' },
    materialSafety: 96, chokingRisk: 90, recallHistory: 98, certificationPresence: 94,
    motorSkills: 88, cognitiveSkills: 86, sensoryEngagement: 78,
    materials: ['Honduran hardwood', 'water-based lacquer', 'sealed neodymium magnets'],
    chokingHazardAssessment: 'All pieces exceed 1.75 inches minimum. Magnets sealed inside wood. Lacquer is non-toxic and chip-resistant. Ages 1+.',
    certifications: ['ASTM F963', 'CPSIA', 'EN-71', 'FSC-certified'],
    pros: ['Beautiful sunset color palette', 'More pieces for complex builds', 'Sustainably made', 'Magnets add creative possibilities'],
    cons: ['Very expensive ($80+)', 'Heavy wooden pieces', 'Magnets can pinch tiny fingers if slammed together'],
    alternativeId: 'review-tegu-14-piece',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B009RKLFCU', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-plantoys-camera',
    _type: 'toyReview',
    productName: 'PlanToys My First Camera',
    brand: 'PlanToys',
    slug: { _type: 'slug', current: 'plantoys-my-first-camera' },
    ageRange: { minMonths: 18, maxMonths: 48 },
    category: { _type: 'reference', _ref: 'cat-educational' },
    materialSafety: 96, chokingRisk: 92, recallHistory: 98, certificationPresence: 92,
    motorSkills: 78, cognitiveSkills: 82, sensoryEngagement: 76,
    materials: ['PlanWood', 'organic pigments', 'rubber lens piece'],
    chokingHazardAssessment: 'One-piece construction with no detachable parts. Lens cap is attached. Kaleidoscope lens is recessed. Safe for 18m+.',
    certifications: ['ASTM F963', 'EN-71', 'ISO 8124'],
    pros: ['Encourages imaginative play', 'Working kaleidoscope viewfinder', 'Beautiful eco-friendly materials', 'Promotes observation skills'],
    cons: ['No actual photos taken', 'Kaleidoscope can be hard for young toddlers to see', 'Limited interactive features'],
    alternativeId: 'review-plantoys-stacking-ring',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B008LWKLOO', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-little-tikes-first-slide',
    _type: 'toyReview',
    productName: 'Little Tikes First Slide',
    brand: 'Little Tikes',
    slug: { _type: 'slug', current: 'little-tikes-first-slide' },
    ageRange: { minMonths: 18, maxMonths: 72 },
    category: { _type: 'reference', _ref: 'cat-outdoor' },
    materialSafety: 84, chokingRisk: 94, recallHistory: 80, certificationPresence: 84,
    motorSkills: 90, cognitiveSkills: 70, sensoryEngagement: 72,
    materials: ['blow-molded polyethylene', 'UV-resistant plastic'],
    chokingHazardAssessment: 'No small parts. Sturdy wide base. Low 3-foot height. Easy-climb steps with texture. Ages 18m+.',
    certifications: ['ASTM F963', 'CPSIA'],
    pros: ['Perfect intro to slides', 'Folds flat for storage', 'Can be used indoors or outdoors', 'Very stable wide base'],
    cons: ['Static electricity in dry weather', 'Limited height for older kids', 'Plastic fades in direct sun'],
    alternativeId: 'review-step2-sandbox',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B004OR1TLA', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-step2-sandbox',
    _type: 'toyReview',
    productName: 'Step2 Naturally Playful Sandbox',
    brand: 'Step2',
    slug: { _type: 'slug', current: 'step2-naturally-playful-sandbox' },
    ageRange: { minMonths: 12, maxMonths: 72 },
    category: { _type: 'reference', _ref: 'cat-outdoor' },
    materialSafety: 84, chokingRisk: 82, recallHistory: 86, certificationPresence: 82,
    motorSkills: 86, cognitiveSkills: 80, sensoryEngagement: 90,
    materials: ['rotomolded polyethylene', 'UV-stabilized plastic'],
    chokingHazardAssessment: 'Sandbox itself has no small parts. Sand toys sold separately should be age-checked. Lid prevents animal access.',
    certifications: ['ASTM F963', 'CPSIA'],
    pros: ['Lid doubles as cover to keep sand clean', 'Bench seating built in', 'Durable construction lasts years', 'Encourages sensory play'],
    cons: ['Very heavy when filled (200+ lbs with sand)', 'Sand not included', 'Can attract insects and animals without lid'],
    alternativeId: 'review-little-tikes-first-slide',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B001BADJNK', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-green-toys-dump-truck',
    _type: 'toyReview',
    productName: 'Green Toys Dump Truck',
    brand: 'Green Toys',
    slug: { _type: 'slug', current: 'green-toys-dump-truck' },
    ageRange: { minMonths: 12, maxMonths: 72 },
    category: { _type: 'reference', _ref: 'cat-outdoor' },
    materialSafety: 96, chokingRisk: 92, recallHistory: 98, certificationPresence: 92,
    motorSkills: 80, cognitiveSkills: 74, sensoryEngagement: 72,
    materials: ['100% recycled milk jugs', 'BPA-free', 'phthalate-free', 'PVC-free'],
    chokingHazardAssessment: 'Large one-piece body. No small parts. Working dump bed is large. No screws or metal parts. Safe for 12m+.',
    certifications: ['ASTM F963', 'CPSIA', 'Made in USA', 'FDA food-contact safe'],
    pros: ['100% recycled and recyclable', 'No metal axles (no rust)', 'Dishwasher safe', 'Made in USA'],
    cons: ['Wheels can squeak on hard floors', 'Single color option', 'Lightweight can flip in wind outdoors'],
    alternativeId: 'review-radio-flyer-wagon',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B001Q2Z2IK', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-fisher-price-smart-chair',
    _type: 'toyReview',
    productName: 'Fisher-Price Laugh & Learn Smart Stages Chair',
    brand: 'Fisher-Price',
    slug: { _type: 'slug', current: 'fisher-price-laugh-learn-smart-stages-chair' },
    ageRange: { minMonths: 12, maxMonths: 36 },
    category: { _type: 'reference', _ref: 'cat-educational' },
    materialSafety: 84, chokingRisk: 86, recallHistory: 80, certificationPresence: 88,
    motorSkills: 78, cognitiveSkills: 86, sensoryEngagement: 82,
    materials: ['BPA-free plastic', 'fabric seat', 'electronic components'],
    chokingHazardAssessment: 'All interactive elements flush-mounted. Book pages thick plastic. Remote is oversized. Battery compartment secured. Ages 12m+.',
    certifications: ['ASTM F963', 'CPSIA', 'FCC compliant'],
    pros: ['Smart Stages adapts to childs level', '50+ songs and phrases', 'Seat lifts for surprise activities', 'Teaches ABCs numbers and shapes'],
    cons: ['Large footprint', 'Battery hungry (3 AA)', 'Weight limit 40 lbs'],
    alternativeId: 'review-leapfrog-learning-friends',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B00CHOL52I', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-vtech-kidibeats',
    _type: 'toyReview',
    productName: 'VTech KidiBeats Drum Set',
    brand: 'VTech',
    slug: { _type: 'slug', current: 'vtech-kidibeats-drum-set' },
    ageRange: { minMonths: 24, maxMonths: 60 },
    category: { _type: 'reference', _ref: 'cat-sensory' },
    materialSafety: 84, chokingRisk: 86, recallHistory: 88, certificationPresence: 86,
    motorSkills: 88, cognitiveSkills: 78, sensoryEngagement: 92,
    materials: ['BPA-free plastic', 'electronic components', 'rubber drum pads'],
    chokingHazardAssessment: 'Drumsticks are large and rounded. All components permanently attached. Battery compartment screw-secured. Ages 2+.',
    certifications: ['ASTM F963', 'CPSIA', 'FCC compliant'],
    pros: ['Teaches rhythm and music', '4 play modes', 'LED lights add visual engagement', 'Develops bilateral coordination'],
    cons: ['Very loud even on low volume', 'Drumsticks stored loosely', 'Limited drum pad sensitivity'],
    alternativeId: 'review-baby-einstein-tunes',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B007XVYSDI', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-manhattan-toy-winkel',
    _type: 'toyReview',
    productName: 'Manhattan Toy Winkel Rattle and Teether',
    brand: 'Manhattan Toy',
    slug: { _type: 'slug', current: 'manhattan-toy-winkel-rattle' },
    ageRange: { minMonths: 0, maxMonths: 18 },
    category: { _type: 'reference', _ref: 'cat-sensory' },
    materialSafety: 90, chokingRisk: 92, recallHistory: 94, certificationPresence: 88,
    motorSkills: 80, cognitiveSkills: 62, sensoryEngagement: 92,
    materials: ['BPA-free polyurethane tubes', 'ABS plastic center'],
    chokingHazardAssessment: 'All loops are continuous with no endpoints. Center rattle is sealed. Entire toy is larger than choking cylinder. Safe from birth.',
    certifications: ['ASTM F963', 'CPSIA', 'CE mark'],
    pros: ['Award-winning design', 'Can be refrigerated for teething relief', 'Lightweight and easy to grasp', 'Multiple loops to grab'],
    cons: ['Tubes can discolor over time', 'Not dishwasher safe', 'Rattle sound is subtle'],
    alternativeId: 'review-manhattan-toy-skwish',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B000BNCA4Y', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-fat-brain-innybin',
    _type: 'toyReview',
    productName: 'Fat Brain Toys InnyBin Shape Sorter',
    brand: 'Fat Brain Toys',
    slug: { _type: 'slug', current: 'fat-brain-toys-innybin' },
    ageRange: { minMonths: 10, maxMonths: 24 },
    category: { _type: 'reference', _ref: 'cat-sensory' },
    materialSafety: 92, chokingRisk: 90, recallHistory: 96, certificationPresence: 88,
    motorSkills: 88, cognitiveSkills: 82, sensoryEngagement: 86,
    materials: ['BPA-free silicone lid', 'ABS plastic shapes', 'ABS plastic cube'],
    chokingHazardAssessment: 'All shapes exceed small parts cylinder. Elastic bands on lid are secured. Cube opening is too small for head entry. Ages 10m+.',
    certifications: ['ASTM F963', 'CPSIA'],
    pros: ['Innovative elastic lid design', 'Teaches shapes and problem solving', 'No wrong way to play', 'Easy for babies to succeed'],
    cons: ['Elastic bands may stretch over time', 'Limited to 6 shapes', 'Shapes can roll under furniture'],
    alternativeId: 'review-fat-brain-dimpl',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B07BFGMP3K', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-melissa-doug-latches',
    _type: 'toyReview',
    productName: 'Melissa & Doug Latches Board',
    brand: 'Melissa & Doug',
    slug: { _type: 'slug', current: 'melissa-doug-latches-board' },
    ageRange: { minMonths: 36, maxMonths: 72 },
    category: { _type: 'reference', _ref: 'cat-educational' },
    materialSafety: 86, chokingRisk: 78, recallHistory: 82, certificationPresence: 88,
    motorSkills: 92, cognitiveSkills: 86, sensoryEngagement: 74,
    materials: ['wood', 'metal latches', 'non-toxic paint'],
    chokingHazardAssessment: 'Metal latches are firmly attached. Doors are hinged and cannot detach. Board is one piece. Ages 3+ due to latch complexity.',
    certifications: ['ASTM F963', 'CPSIA', 'CE mark'],
    pros: ['Teaches real-world latch skills', 'Builds fine motor strength', 'Hidden pictures behind each door', 'Durable wood construction'],
    cons: ['Metal latches can pinch small fingers', 'Paint can chip at hinges over time', 'Large and heavy board'],
    alternativeId: 'review-hape-shape-sorter-xylophone',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B000GKA9A6', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-hape-shape-sorter-xylophone',
    _type: 'toyReview',
    productName: 'Hape Shape Sorter Xylophone and Piano',
    brand: 'Hape',
    slug: { _type: 'slug', current: 'hape-shape-sorter-xylophone' },
    ageRange: { minMonths: 12, maxMonths: 36 },
    category: { _type: 'reference', _ref: 'cat-educational' },
    materialSafety: 94, chokingRisk: 86, recallHistory: 96, certificationPresence: 92,
    motorSkills: 90, cognitiveSkills: 84, sensoryEngagement: 86,
    materials: ['sustainable wood', 'water-based paint', 'metal xylophone keys'],
    chokingHazardAssessment: 'Shape blocks are oversized. Mallet is thick-handled. Xylophone keys permanently attached. Sorting holes match shapes. Ages 12m+.',
    certifications: ['ASTM F963', 'EN-71', 'FSC certified'],
    pros: ['3-in-1 toy: sorter, xylophone, piano', 'Beautiful wood and paint quality', 'Teaches shapes, colors, and music', 'Award-winning design'],
    cons: ['Shape blocks can roll away', 'Metal keys produce loud sounds', 'Piano function requires precision'],
    alternativeId: 'review-melissa-doug-latches',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B0079PC6AE', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-skip-hop-bandana-buddies',
    _type: 'toyReview',
    productName: 'Skip Hop Bandana Buddies Activity Toy',
    brand: 'Skip Hop',
    slug: { _type: 'slug', current: 'skip-hop-bandana-buddies' },
    ageRange: { minMonths: 0, maxMonths: 18 },
    category: { _type: 'reference', _ref: 'cat-sensory' },
    materialSafety: 88, chokingRisk: 86, recallHistory: 90, certificationPresence: 84,
    motorSkills: 76, cognitiveSkills: 68, sensoryEngagement: 90,
    materials: ['polyester fabric', 'BPA-free silicone teether', 'crinkle material'],
    chokingHazardAssessment: 'Stroller clip is adult-strength. Teether is oversized and attached. All parts sewn securely. No detachable pieces. Birth+.',
    certifications: ['ASTM F963', 'CPSIA'],
    pros: ['Multi-texture sensory features', 'Attached teether for on-the-go', 'Clips to stroller or car seat', 'Crinkle and rattle sounds'],
    cons: ['Fabric absorbs drool and needs frequent washing', 'Clip can be stiff', 'Limited use past 18 months'],
    alternativeId: 'review-lamaze-freddie',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B013GY4ZJO', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-b-toys-squeeze-blocks',
    _type: 'toyReview',
    productName: 'B. toys One Two Squeeze Soft Blocks',
    brand: 'B. toys',
    slug: { _type: 'slug', current: 'b-toys-one-two-squeeze-blocks' },
    ageRange: { minMonths: 6, maxMonths: 36 },
    category: { _type: 'reference', _ref: 'cat-building' },
    materialSafety: 90, chokingRisk: 92, recallHistory: 92, certificationPresence: 86,
    motorSkills: 80, cognitiveSkills: 76, sensoryEngagement: 84,
    materials: ['BPA-free soft plastic', 'phthalate-free', 'food-grade inks'],
    chokingHazardAssessment: 'Each block is 2+ inches on all sides. Soft and squeezable. Numbers and animals are printed (not raised). Safe for 6m+.',
    certifications: ['ASTM F963', 'CPSIA', 'Phthalate-free certified'],
    pros: ['Soft and safe for mouthing', 'Teaches numbers and animals', 'Stackable and squeezable', 'Easy to clean'],
    cons: ['Soft blocks dont stack as high as hard ones', 'Can attract dust', 'Images fade with heavy chewing'],
    alternativeId: 'review-b-toys-bristle-blocks',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B01LWOFWN8', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-infantino-flip-peek-phone',
    _type: 'toyReview',
    productName: 'Infantino Flip & Peek Fun Phone',
    brand: 'Infantino',
    slug: { _type: 'slug', current: 'infantino-flip-peek-fun-phone' },
    ageRange: { minMonths: 3, maxMonths: 24 },
    category: { _type: 'reference', _ref: 'cat-educational' },
    materialSafety: 86, chokingRisk: 88, recallHistory: 90, certificationPresence: 84,
    motorSkills: 74, cognitiveSkills: 76, sensoryEngagement: 80,
    materials: ['BPA-free plastic', 'electronic components', 'soft-touch buttons'],
    chokingHazardAssessment: 'Flip screen is attached. All buttons are flush. No detachable parts. Battery screw-secured. Safe for 3m+.',
    certifications: ['ASTM F963', 'CPSIA', 'FCC compliant'],
    pros: ['Peek-a-boo mirror inside', 'Realistic phone buttons', 'Plays music and sounds', 'Very affordable'],
    cons: ['Limited sounds (3 melodies)', 'Plastic feels flimsy', 'Mirror is small'],
    alternativeId: 'review-leapfrog-learning-friends',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B075XGSL4X', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-lego-duplo-steam-train',
    _type: 'toyReview',
    productName: 'LEGO DUPLO Steam Train',
    brand: 'LEGO DUPLO',
    slug: { _type: 'slug', current: 'lego-duplo-steam-train' },
    ageRange: { minMonths: 24, maxMonths: 60 },
    category: { _type: 'reference', _ref: 'cat-building' },
    materialSafety: 92, chokingRisk: 90, recallHistory: 92, certificationPresence: 96,
    motorSkills: 86, cognitiveSkills: 84, sensoryEngagement: 80,
    materials: ['ABS plastic', 'BPA-free', 'electronic motor', 'rubber wheels'],
    chokingHazardAssessment: 'DUPLO-sized bricks and figures. Push-and-go motor built in. Track pieces are large. Battery compartment secured. Ages 2+.',
    certifications: ['ASTM F963', 'EN-71', 'CPSIA', 'ISO 8124'],
    pros: ['App-connected for modern play', 'Push-and-go motorized engine', 'Sound effects enhance play', '59 pieces with track'],
    cons: ['Requires 4 AAA batteries', 'App can be glitchy', 'Track takes up significant floor space'],
    alternativeId: 'review-lego-duplo-number-train',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B07FNNNQS4', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
  {
    _id: 'review-crayola-finger-paints',
    _type: 'toyReview',
    productName: 'Crayola Washable Finger Paints (6 Count)',
    brand: 'Crayola',
    slug: { _type: 'slug', current: 'crayola-washable-finger-paints' },
    ageRange: { minMonths: 24, maxMonths: 72 },
    category: { _type: 'reference', _ref: 'cat-educational' },
    materialSafety: 86, chokingRisk: 84, recallHistory: 92, certificationPresence: 90,
    motorSkills: 86, cognitiveSkills: 82, sensoryEngagement: 92,
    materials: ['water-based paint', 'non-toxic pigments', 'binding agents'],
    chokingHazardAssessment: 'Liquid paint in squeeze tubes. Caps are large. Non-toxic if ingested in small amounts. Supervision required. Ages 2+.',
    certifications: ['ASTM D-4236', 'AP certified non-toxic', 'CPSIA'],
    pros: ['Truly washable from skin and most fabrics', 'Vibrant colors', 'Thick texture perfect for little fingers', 'Encourages sensory exploration'],
    cons: ['Can stain porous surfaces', 'Tubes can be squeezed too hard making mess', 'Dries out if left open'],
    alternativeId: 'review-play-doh-starter',
    affiliateLinks: [{ _type: 'affiliateLink', partnerId: 'amazon', url: 'https://amazon.com/dp/B000REI1FU', tag: 'safeneststore-20' }],
    hasActiveRecall: false, needsReview: false,
  },
];

// Compute scores for all reviews
reviews.forEach(r => {
  r.safetyScore = computeSafetyScore(r.materialSafety, r.chokingRisk, r.recallHistory, r.certificationPresence);
  r.developmentScore = computeDevelopmentScore(r.motorSkills, r.cognitiveSkills, r.sensoryEngagement);
});

async function seed() {
  console.log('🌱 Seeding 30 new toy reviews to Sanity...\n');

  // Phase 1: Create all reviews without alternatives
  console.log('Phase 1: Creating reviews...\n');
  for (const review of reviews) {
    const { alternativeId, ...doc } = review;
    await client.createOrReplace(doc);
    console.log(`  ✓ ${review.productName} (Safety: ${review.safetyScore}, Dev: ${review.developmentScore})`);
  }

  // Phase 2: Patch alternatives
  console.log('\nPhase 2: Linking alternatives...\n');
  for (const review of reviews) {
    if (review.alternativeId) {
      await client.patch(review._id).set({
        alternatives: [{ _type: 'reference', _ref: review.alternativeId }]
      }).commit();
      console.log(`  ✓ ${review._id} → ${review.alternativeId}`);
    }
  }

  console.log('\n✅ Done! 30 new reviews created (total: 50 products).');
}

seed().catch(err => { console.error('❌ Error:', err.message); process.exit(1); });
